# Site settings
title: "Kapish Resume"
description: "Kapish Malik Online Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kapish Malik"
resume_title:                   "Software Developer"
resume_contact_email:           "kapish15026@iiitd.ac.in"
resume_contact_telephone:       "91-9711498211"
resume_contact_address:         ""
resume_header_contact_info: "kapish15026@iiitd.ac.in"
resume_header_intro: "<p>Extremely passionate about problem solving, designing and developing core software systems that drive the business. Excited to be a part of the landscape where web and mobile technologies are changing the lives of humans.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/"
  #resume_dribbble_url:          "https://dribbble.com/"
  resume_facebook_url:          "https://www.facebook.com/kapish.malik"
  resume_linkedin_url:          "https://www.linkedin.com/in/kapish-malik-b06b9341/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://kapishmalik.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman